#!/bin/bash

sudo apt-get -y install update-notifier keepassx preload prelink gdebi gnome-disk-utility gparted
sudo apt-get -y install aspell aspell-en aspell-es gufw shutter gimp vlc icedtea-7-plugin openjdk-7-jre
sudo apt-get -y install chromium chromium-l10n
sudo apt-get -y install libreoffice libreoffice-help-es libreoffice-l10n-es
sudo apt-get -y remove iceweasel

#sudo apt-get -y install apt-transport-https
