#!/bin/bash
######## installpackages - Installs packages & necessary repos - script 1

#### Remove all your repos
#sudo rm -f -r /etc/apt/sources.list.d/*

#### Upgrading system
#sudo apt-get -y update
#sudo apt-get -y upgrade
##sudo apt-get -y dist-upgrade
##sudo apt-get -y install xxx --no-remove --force-yes

######## Backup & Sync

#

######## OS & Utilities

#### apt-fast
apps1/apt-fast

#### synaptic
sudo apt-fast -y install synaptic

#### preload
sudo apt-fast -y install preload

#### prelink
sudo apt-fast -y install prelink

#### gdebi
sudo apt-fast -y install gdebi

#### gnome-disk-utility
sudo apt-fast -y install gnome-disk-utility

#### gparted
sudo apt-fast -y install gparted

#### update-notifier
sudo apt-fast -y install update-notifier

######## Desktop Environment

#

######## Themes

#### vibrancy-colors icon theme
apps1/vibrancy-colors

######## Language packages
#sudo apt-fast -y install myspell-es wspanish language-pack-es language-pack-es-base 
#sudo apt-fast -y install myspell-en-gb myspell-en-us
sudo apt-fast -y install aspell aspell-en aspell-es

######## Security & Privacy

#### gufw
sudo apt-fast -y install gufw

######## CD/DVD Tools

#

######## Photos & Graphics

#### shutter
sudo apt-fast -y install shutter

#### gimp
apps1/gimp

######## Audio & Music

#

######## Videos & Movies

#

######## All multimedia content

#### vlc-stable
apps/vlc-stable

######## Development

#### openjdk-7
sudo apt-fast -y install icedtea-7-plugin openjdk-7-jre

######## Web Browsers

#### google-chrome-stable
#apps1/google-chrome-stable

#### google-chrome-unstable
#apps1/google-chrome-unstable

#### chromium stable
sudo apt-fast -y install chromium-browser chromium-browser-l10n chromium-codecs-ffmpeg-extra

#### ubuntu-mozilla-security
apps1/ubuntu-mozilla-security

#### pepper-flash-for-chromium
sudo apt-fast -y install pepperflashplugin-nonfree

#### pepper-flash-for-firefox
apps1/pepper-flash-for-firefox

######## Social

#

######## File Management

#### Various
#sudo apt-fast -y install rar unrar unace p7zip-full p7zip-rar sharutils mpack arj cabextract		#p7zip

######## File Sharing

#

######## News & Books

#

######## Office & Productivity

#### libreoffice
apps1/libreoffice

#### qpdfview
sudo apt-fast -y install qpdfview

######## Games

#

######## Extra

#### uninstallpackages
sudo apt-fast -y remove iceweasel #pidgin* thunderbird* adobe-flashplugin flashplugin-nonfree-extrasound flashplugin-installer shotwell

#### Upgrading system
#sudo apt-get -y upgrade
#sudo apt-get -y dist-upgrade

#### Repairing system 2/2
#sudo apt-get -f install

#### Cleaning system
#sudo apt-get -f install
sudo apt-get -y autoremove
#sudo apt-get -y autoclean
#sudo apt-get -y clean
