#!/bin/bash

#### gimp
sudo add-apt-repository -y ppa:otto-kesselgulasch/gimp
sudo sed -i 's/jessie/vivid/g' /etc/apt/sources.list.d/*.list
sudo apt-fast -y update
sudo apt-fast -y install gimp #gimp-plugin-registry gimp-help-es