#!/bin/bash

#### graphics-drivers-team - Possibly Unstable
sudo add-apt-repository -y ppa:graphics-drivers/ppa
sudo apt-fast -y update
sudo sed -i 's/jessie/vivid/g' /etc/apt/sources.list.d/*.list
sudo apt-fast -y dist-upgrade