#!/bin/bash

#### krita-testing
sudo add-apt-repository -y ppa:dimula73/krita
sudo apt-fast -y update
sudo sed -i 's/jessie/vivid/g' /etc/apt/sources.list.d/*.list
sudo apt-fast -y install krita-testing
sudo mv /usr/share/applications/kde4/krita.desktop /usr/share/applications/