#!/bin/bash

#### libreoffice
#sudo add-apt-repository -y ppa:libreoffice/libreoffice-prereleases
sudo add-apt-repository -y ppa:libreoffice/ppa
sudo sed -i 's/jessie/vivid/g' /etc/apt/sources.list.d/*.list
sudo apt-fast -y update
sudo apt-fast -y install libreoffice libreoffice-help-es libreoffice-l10n-es