#!/bin/bash

#### notepadqq
sudo add-apt-repository -y ppa:notepadqq-team/notepadqq
sudo sed -i 's/jessie/vivid/g' /etc/apt/sources.list.d/*.list
sudo apt-fast -y update
sudo apt-fast -y install notepadqq notepadqq-gtk