#!/bin/bash

#### oibaf - Possibly Unstable
sudo add-apt-repository -y ppa:oibaf/graphics-drivers
sudo sed -i 's/jessie/vivid/g' /etc/apt/sources.list.d/*.list
sudo apt-fast -y update
sudo apt-fast -y dist-upgrade