#!/bin/bash

#### pepper-flash-for-firefox
sudo add-apt-repository -y ppa:nilarimogard/webupd8
sudo sed -i 's/jessie/vivid/g' /etc/apt/sources.list.d/*.list
sudo apt-fast -y update
sudo apt-fast -y install pepperflashplugin-nonfree freshplayerplugin