#!/bin/bash

#### vibrancy-colors icon theme
sudo add-apt-repository -y ppa:ravefinity-project/ppa
sudo sed -i 's/jessie/vivid/g' /etc/apt/sources.list.d/*.list
sudo apt-fast -y update
sudo apt-fast install vibrancy-colors