#!/bin/bash

#### vlc-daily
sudo add-apt-repository -y ppa:videolan/master-daily
sudo sed -i 's/jessie/vivid/g' /etc/apt/sources.list.d/*.list
sudo apt-fast -y update
sudo apt-fast -y install vlc vlc-plugin-pulse libvlc5