#!/bin/bash

#### ddrescue-gui
sudo add-apt-repository -y ppa:hamishmb/myppa
sudo sed -i 's/jessie/vivid/g' /etc/apt/sources.list.d/*.list
sudo apt-fast -y update
sudo apt-fast -y install ddrescue-gui