#!/bin/bash

#### grub-customizer
sudo add-apt-repository -y ppa:danielrichter2007/grub-customizer
sudo sed -i 's/jessie/vivid/g' /etc/apt/sources.list.d/*.list
sudo apt-fast -y update
sudo apt-fast -y install grub-customizer