#!/bin/bash

#### kicad
#sudo add-apt-repository -y ppa:js-reynaud/kicad-package-daily-stable
#sudo add-apt-repository -y ppa:adamwolf/kicad-trusty-backports
sudo add-apt-repository -y ppa:js-reynaud/ppa-kicad
sudo sed -i 's/jessie/vivid/g' /etc/apt/sources.list.d/*.list
sudo apt-fast -y update
sudo apt-fast -y install kicad