#!/bin/bash

#### tlp
sudo add-apt-repository -y ppa:linrunner/tlp
sudo sed -i 's/jessie/vivid/g' /etc/apt/sources.list.d/*.list
sudo apt-fast -y update
sudo apt-fast -y install tlp tlp-rdw
##sudo tlp start