#!/bin/bash

#### unetbootin
sudo add-apt-repository -y ppa:n-muench/programs-ppa
sudo sed -i 's/jessie/vivid/g' /etc/apt/sources.list.d/*.list
sudo apt-fast -y update
sudo apt-fast -y install unetbootin